name: TwosideKeeper
main: sig.plugin.TwosideKeeper.TwosideKeeper
version: 3.11.1f
loadbefore: [aPlugin]
commands:
   money:
      description: Tells the player the amount of money they are holding.
      usage: /money
      permission: TwosideKeeper.money
      permission-message: You don't have permission to check your balance!
   enchant_advanced:
      description: Enchants items with more properties.
      usage: /enchant_advanced <enchantment> <level>
      permission: TwosideKeeper.enchant
      permission-message: No permissions!
   harden_armor:
      description: Hardens a piece of armor.
      usage: /harden_armor <breaks>
      permission: TwosideKeeper.harden
      permission-message: No permissions!
   item_cube:
      description: Sets this item as an item cube.
      usage: /item_cube <id>
      permission: TwosideKeeper.item_cube
      permission-message: No permissions!
   artifact:
      description: Gives the player an artifact.
      usage: /artifact <ArtifactType> [amt]
      permission: TwosideKeeper.artifact
      permission-message: No permissions!
   recyclingcenter:
      description: Defines a new container for a Recycling Center.
      usage: /recyclingcenter
      permission: TwosideKeeper.recyclingcenter
      permission-message: No permissions!
   glowingitem:
      description: Creates a new glowing item.
      usage: /glowingitem
      permission: TwosideKeeper.glowingitem
      permission-message: No permissions!
   sound:
      description: Toggle sound message notifications.
      usage: /sound
      permission: TwosideKeeper.sound
      permission-message: No permissions!
   log:
      description: Adjusts the debugging log level for TwosideKeeper in the console.
      usage: /log
      permission: TwosideKeeper.log
      permission-message: No permissions!
   servertype:
      description: Sets the server type to another type.
      usage: /servertype <MAIN|TEST|QUIET>
      permission: TwosideKeeper.servertype
      permission-message: No permissions!
   ess:
      description: Generates a Mysterious Essence report.
      usage: /ess
      permission: TwosideKeeper.report
      permission-message: No permissions!
   bow:
      description: Generates a Bow report.
      usage: /bow
      permission: TwosideKeeper.report
      permission-message: No permissions!
   loot:
      description: Generates a Loot report.
      usage: /loot
      permission: TwosideKeeper.report
      permission-message: No permissions!
   mega:
      description: Generates a Mega Piece.
      usage: /mega <MATERIAL> <false|true>
      permission: TwosideKeeper.mega
      permission-message: No permissions!
   fix:
      description: Does many things depending on what item is being held. Typically if it's broken, typing this will help.
      usage: /fix
      permission: TwosideKeeper.fix
      permission-message: No permissions!
   tp_world:
      description: Teleports to a location in a specified world.
      usage: /tp_world <world> <x> <y> <z>
      permission: TwosideKeeper.tp_world
      permission-message: No permissions!
   stats:
      description: Display statistics for damage and defense.
      usage: /stats [username]
      permission: TwosideKeeper.money
      permission-message: No permissions!
   awakenedartifact:
      description: Used for upgrading awakened artifacts.
      usage: /awakenedartifact
      permission: TwosideKeeper.money
      permission-message: No permissions!
   awakenedartifact_ability:
      description: Apply an awakened artifact ability to an item.
      usage: /awakenedartifact_ability <ABILITY> <level>
      permission: TwosideKeeper.artifact
      permission-message: No permissions!
   mode:
      description: Displays information about a mode.
      usage: /mode <modename>
      permission: TwosideKeeper.money
      permission-message: No permissions!
   dps:
      description: DPS Logger.
      usage: /dps
      permission: TwosideKeeper.money
      permission-message: No permissions!
   muchlogsmuchwow:
      description: D00d.
      usage: /muchlogsmuchwow
      permission: TwosideKeeper.muchlogsmuchwow
      permission-message: No permissions!
   make_set_item:
      description: Turns an item into a set.
      usage: /make_set_item <SET> <TIER>
      permission: TwosideKeeper.makesetitem
      permission-message: No permissions!
   craft:
      description: Displays the crafting recipe for a custom item. Press Tab after typing /craft to see options.
      usage: /craft ITEM
      permission: TwosideKeeper.money
      permission-message: No permissions!
   weather:
      description: Toggles the sending of a weather warning message to the player.
      usage: /weather <DISCORD NAME>
      permission: TwosideKeeper.money
      permission-message: No permissions!
   red:
      description: Ready up for the ice skating race.
      usage: /red
      permission: TwosideKeeper.money
      permission-message: No permissions!
   ready:
      description: Ready up for the tree climbing race.
      usage: /ready
      permission: TwosideKeeper.money
      permission-message: No permissions!
   habitat:
      description: View the habitat levels within the area.
      usage: /habitat
      permission: TwosideKeeper.money
      permission-message: No permissions!
   debugreport:
      description: View a full debug report of the Server.
      usage: /debugreport
      permission: TwosideKeeper.fulldebugreport
      permission-message: No permissions!
   equip_weapon:
      description: Toggle Automatic Equipping of Weapons
      usage: /equip_weapon
      permission: TwosideKeeper.money
      permission-message: No permissions!
   equip_armor:
      description: Toggle Automatic Equipping of Armor
      usage: /equip_armor
      permission: TwosideKeeper.money
      permission-message: No permissions!
   options:
      description: Displays a menu to toggle plugin-specific options.
      usage: /options
      permission: TwosideKeeper.money
      permission-message: No permissions!
   settings:
      description: Displays a menu to toggle plugin-specific options.
      usage: /settings
      permission: TwosideKeeper.money
      permission-message: No permissions!
   damage_numbers:
      description: Toggles the damage numbers that display while dealing damage.
      usage: /damage_numbers
      permission: TwosideKeeper.money
      permission-message: No permissions!
   dailyloot:
      description: Loots a certain box.
      usage: /dailyloot <UUID>
      permission: TwosideKeeper.money
      permission-message: No permissions!
   pvp:
      description: Declare PvP to a player.
      usage: /pvp
      permission: TwosideKeeper.money
      permission-message: No permissions!