package sig.plugin.TwosideKeeper.HelperStructures;

public enum ArtifactItem {
	MYSTERIOUS_ESSENCE,
	ARTIFACT_ESSENCE,
	ARTIFACT_CORE,
	ARTIFACT_BASE,
	ANCIENT_ESSENCE,
	ANCIENT_CORE,
	ANCIENT_BASE,
	LOST_ESSENCE,
	LOST_CORE,
	LOST_BASE,
	DIVINE_ESSENCE,
	DIVINE_CORE,
	DIVINE_BASE,
	MALLEABLE_BASE,
	ARTIFACT_RECIPE;
}
